### ISSUE TITLE
Adjust Soundtrap data with a calibration file

### ISSUE THREAD

**Issue by mfwgauger** [lifewatch/pyhydrophone#31]
Please add the possibility to adjust calibration of Soundtrap data with a calibration file.

**Comment by cparcerisas** [comment]
This only applied to SoundTrapHF class. Which is necessary for pyporcc and reading soundtrap click detections.

Regarding the use of the calibration file in pyporcc
Just so you know how this calibration thing is working, the idea right now for the packages is that a flat value calibration is used during processing. This is done because the conversion to uPa is done in the time domain (directly on the raw signal) and to apply a frequency-dependent calibration one would need to compute the spectrogram, calibrate, and then re-compute the signal. 
So far, how we're dealing with it is using the flat calibration value for all the operations and then apply the frequency-dependent calibration to the frequency-dependent results. This can be done as shown in this example (pyhydrophone computes for you the difference between flat calibration and freq-dependent calibration) : 
https://github.com/lifewatch/pyhydrophone/blob/main/examples/plot_freq_calibration.py

This last step is currently not implemented in an automatic way in pyporcc. There it would then be applied during the classification of the clicks, where a spectrum is computed (not during the detection of all the possible clicks).

**Comment by cparcerisas** [comment]
https://github.com/lifewatch/pyporcc/issues/14#issue-2505789742
